### ISSUE TITLE
Add usage example to readme

### ISSUE THREAD

**Issue by mirchow** [continuationlabs/swagger-jacker#1]
Hey Colin. What a great idea! Thanks for writing this library. Can you please add an example of how to use it or point me to a project that uses this library? Thanks.

**Comment by cjihrig** [comment]
Hey Mirek! I guess my surprise for my next visit is ruined :-D

The project is still very early stages, hence the lack of documentation, etc., but it should be safe to start experimenting with. Here is a sample server:

```javascript
'use strict';

const Celebrate = require('celebrate');
const Express = require('express');
const Joi = require('joi');
const SwaggerJacker = require('swagger-jacker');
const app = Express();

SwaggerJacker(app);

app.get('/', (req, res) => { res.send('Hello World!'); });
app.get('/customers', (req, res) => { res.send('Get all customers'); });

app.get('/schema', Celebrate({
  headers: { 'x-forwarded-for': Joi.string().optional().description('forwarded for') },
  query: { foo: Joi.string().required().description('the foo param') },
  params: { bar: Joi.string().required().description('the bar param') },
  body: { baz: Joi.string().required() }
}), (req, res) => { res.send('passed validation'); });

app.listen(3000, () => { console.log('Listening!'); });
```

Really, the only thing you need to do is `require()` this module, then pass your `app` to it.

**Comment by mirchow** [comment]
Awesome. Got it working. It's great that you are coming on site as well. Thanks for the example.

**Comment by lironess** [comment]
example is broken.
try yourself to make a request to /schema with swagger ui.
